### PR TITLE
Add manpage for vzvol(1)

### PR DESCRIPTION
**Pull request by Alhadis**
Sorry for taking so long, I nearly forgot. 😅

You can see a "stylised TTY preview" [here](https://cdn.rawgit.com/Alhadis/0211a1cfc77e1ff4bd5a4f8f5e32b0d4/raw/57866c2f58051806b60361c96e07a7cbe23eab53/vzvol.1.html).

I'll leave it for you to decide how the installers should be updated. =)

### CODE REVIEW

**Comment by Alhadis** [comment]
... if you prefer I pick a less convoluted-looking macro package, I'd be happy to use `man(7)` or something. 😜

I made a point of using `mdoc` because of its dominance in the BSD world, and the fact that OpenBSD officially deprecated use of the legacy `man` macros because it lacks support for semantic markup.

But if you don't know a single line of Roff, I sorely doubt you give a shit. 😀

(should probably watch my tone, nobody on GitHub knows we're friends from way back... 😓)

**Comment by RainbowHackerHorse** [comment]
Yeah, I'm not picky, though I'd like to be able to update it myself eventually.
This is planned to be introduced in the 0.7.0 release, though it'll need to be updated to properly document new features, and remove deprecated or no longer available functions

**Comment by RainbowHackerHorse** [comment]
also, being that this is a tool that can only be run as root or via sudo, it should be vzvol(8), not vzvol(1)

**Comment by RainbowHackerHorse** [comment]
I should probably move it to /usr/local/sbin as well...

**Comment by RainbowHackerHorse** [comment]
a txt2man variant of this PR has been added on docs/add-manpage, and will be merged post-testing
forgot to mention this earlier.

**Pull request closed without merging**
